http://localhost:4004

###

http://localhost:4004/blocks

###

POST http://localhost:4004/blocks

{
    "message": "Data for my block"
}
###
http://localhost:4004/blocks/1

###
http://localhost:4004/blocks/4
