http://localhost:4004

###

http://localhost:4004/blocks

###

POST http://localhost:4004/blocks

{
    "message": "Data for my block"
}
###
http://localhost:4004/blocks/1

###
http://localhost:4004/blocks/8f1528b2a70c2badc96565c55e88f7feeee20e9a6c03156cc4d5e5c87fc963c9
